import type { IProject, IExperience, IEducation, ISkillGroup } from "@portfolio/shared";

export const DEVELOPER_PROFILE = {
  name: "Abhimanyu Kumar",
  role: "Software Engineer",
  title: "Software Engineer | Python • FastAPI • React • Linux • Observability",
  headline: "Building Resilient Enterprise Telemetry, High-Performance APIs, and Modern Reactive UIs",
  bio: "Software Engineer with 1.5+ years of enterprise technology experience specializing in observability engineering, distributed telemetry collection, and full-stack systems. Hands-on with Python, FastAPI, React, Linux/RHEL, InfluxDB, Grafana, Prometheus, Docker/Podman, and Enterprise Storage & SAN fabrics (NetApp, Dell EMC, Hitachi, Brocade). Currently pursuing M.Tech at BITS Pilani through Wipro WILP.",
  email: "akabhimanyukumar111@gmail.com",
  phone: "+91 8825212001",
  location: "India",
  status: "Operational // Open to High-Impact Opportunities",
  github: "https://github.com/abhimanyu840",
  linkedin: "https://linkedin.com/in/abhimanyukumar",
  portfolio: "https://abhimanyukumarportfolio.netlify.app/",
  uptimeStart: "2024-01-01T00:00:00.000Z",
};

export const SEED_PROJECTS: IProject[] = [
  {
    id: "unified-ops",
    slug: "unified-ops",
    title: "UnifiedOps — Enterprise Infrastructure Monitoring Platform",
    tagline: "Centralized monitoring platform for alerts, storage systems, SAN ports, and performance metrics",
    description:
      "A production-grade enterprise infrastructure telemetry platform designed to centralize telemetry across diverse SAN storage platforms (NetApp, Dell EMC, Hitachi) and Brocade SAN switches. Implements automated alert classification, real-time port health metrics, and high-density operational dashboards.",
    category: "observability",
    tags: ["Python", "FastAPI", "React", "TypeScript", "InfluxDB", "Grafana", "Prometheus", "SQLite"],
    architecture: [
      "FastAPI Asynchronous Microservice Layer",
      "InfluxDB Time-Series Storage for Sub-Second Metrics",
      "React + TypeScript Dynamic Ops Console",
      "Prometheus Alert Rule Aggregator",
    ],
    highlights: [
      "Centralized real-time monitoring and alerting for enterprise storage arrays and SAN switch fabrics.",
      "Engineered async Python background ingestion workers capable of handling high event bursts.",
      "Implemented historical time-series pre-aggregation and memory-caching strategies, reducing dashboard load times by 68%.",
      "Configured multi-tier alerting pipelines targeting SNMP traps, Syslog relays, and webhook endpoints.",
    ],
    metrics: {
      "Query Latency": "< 45ms",
      "Monitored Nodes": "500+ Nodes",
      "System Uptime": "99.95%",
      "Throughput": "8,500 ev/s",
    },
    githubUrl: "https://github.com/abhimanyu840",
    liveUrl: "https://abhimanyukumarportfolio.netlify.app/",
    featured: true,
    order: 1,
  },
  {
    id: "observatory",
    slug: "observatory",
    title: "Observatory — Infrastructure Observability Platform",
    tagline: "Telemetry collector, time-series pipeline, and Grafana visualization engine",
    description:
      "An end-to-end infrastructure observability suite built for enterprise Linux (RHEL) environments. Coordinates system-level telemetry daemons, network probe pollers, and InfluxDB time-series storage to provide granular real-time visibility into CPU, memory, SAN port traffic, and I/O bottlenecks.",
    category: "observability",
    tags: ["Python", "InfluxDB", "Grafana", "Prometheus", "Linux/RHEL", "Syslog", "SNMP"],
    architecture: [
      "Custom Python Ingestion Daemons (systemd-managed)",
      "InfluxDB 2.x Bucket Sharding & Retention Policies",
      "Prometheus Exporters & Metric Scrapers",
      "Automated Grafana Dashboards as Code",
    ],
    highlights: [
      "Built telemetry daemons in Python that collect system, network, and storage counters with minimal daemon overhead (<1% CPU).",
      "Configured Grafana monitoring dashboards with custom PromQL and Flux queries for storage and SAN port utilization.",
      "Integrated Syslog and SNMP listener pipelines to parse and correlate hardware warnings before component failures.",
    ],
    metrics: {
      "Ingestion Rate": "12,000 metrics/s",
      "Dashboards": "20+ Custom Panels",
      "Retention": "365-Day Retention",
      "Daemon Footprint": "< 25MB RAM",
    },
    githubUrl: "https://github.com/abhimanyu840",
    liveUrl: "https://abhimanyukumarportfolio.netlify.app/",
    featured: true,
    order: 2,
  },
  {
    id: "enterprise-ai-chatbot",
    slug: "enterprise-ai-chatbot",
    title: "Enterprise AI Chatbot & Knowledge Assistant",
    tagline: "Context-aware RAG system tailored for corporate knowledge repositories",
    description:
      "An intelligent conversational assistant engineered to provide verified corporate knowledge retrieval over Microsoft 365 and SharePoint repositories. Evaluated local LLM inference engines (Ollama, NVIDIA NIM) to ensure zero data leakage for on-premise deployments.",
    category: "ai",
    tags: ["Python", "RAG", "LLMs", "React", "SharePoint", "Ollama", "NVIDIA NIM", "Vector Search"],
    architecture: [
      "Dense Vector Embedding Pipeline (BGE / nomic-embed)",
      "Contextual Text Chunking & Semantic Vector Store",
      "Microsoft Graph API Document Sync Service",
      "React Conversational Streaming Interface",
    ],
    highlights: [
      "Designed secure RAG retrieval pipeline incorporating metadata filters and citation provenance tracking.",
      "Benchmarked on-premise LLMs (Llama 3, Mistral) via Ollama and NVIDIA NIM against proprietary cloud models.",
      "Achieved high relevance answers with verifiable reference links directly to underlying SharePoint documents.",
    ],
    metrics: {
      "Retrieval Accuracy": "94.2%",
      "Knowledge Base": "50,000+ Documents",
      "Avg Response Time": "1.2s",
      "On-Premise Privacy": "100% Air-Gapped Ready",
    },
    githubUrl: "https://github.com/abhimanyu840",
    liveUrl: "https://abhimanyukumarportfolio.netlify.app/",
    featured: true,
    order: 3,
  },
  {
    id: "interest-business-platform",
    slug: "interest-business-platform",
    title: "Interest Business Handling Platform & Mobile App",
    tagline: "Type-safe financial calculation system with real-time compound interest engines",
    description:
      "A dual-platform finance and ledger tracking suite comprising a responsive Next.js web application and a React Native Android app. Delivers automated compound and simple interest calculation, late penalty accrual, and live ledger balances with end-to-end Zod validation.",
    category: "fullstack",
    tags: ["Next.js", "React Native", "TypeScript", "Node.js", "Express.js", "MongoDB", "Zod", "NextAuth"],
    architecture: [
      "Next.js App Router Web Portal",
      "React Native Cross-Platform Mobile Client",
      "Express.js & MongoDB Calculation Microservice",
      "Shared Zod Validation Schemas",
    ],
    highlights: [
      "Engineered automated interest calculation engine supporting daily, monthly, and compounded repayment schedules.",
      "Created real-time ledger updates with automatic fine/penalty calculation and PDF statement generation.",
      "Enforced 100% schema validation across frontend and mobile forms using shared Zod contracts.",
    ],
    metrics: {
      "Calculation Accuracy": "100.00%",
      "Platforms": "Web & Android",
      "Ledger Speed": "35ms",
      "Validation": "Strict Type-Safe",
    },
    githubUrl: "https://github.com/abhimanyu840",
    liveUrl: "https://abhimanyukumarportfolio.netlify.app/",
    featured: false,
    order: 4,
  },
  {
    id: "ed-tech-platform",
    slug: "ed-tech-platform",
    title: "Ed-Tech Online Learning & Course Management System",
    tagline: "Scalable MERN learning portal with role-based administrative workflows",
    description:
      "A full-stack learning platform enabling instructors to publish modular multimedia courses and students to track their progress interactively. Features JWT authentication, administrative dashboards, and responsive styling with Tailwind CSS.",
    category: "fullstack",
    tags: ["MERN", "MongoDB", "Express.js", "React", "Node.js", "Tailwind CSS", "JWT", "Mongoose"],
    architecture: [
      "Node.js & Express RESTful API",
      "MongoDB Normalized Schema Architecture",
      "React Single Page Application",
      "Tailwind CSS Responsive Design",
    ],
    highlights: [
      "Implemented secure JWT authentication and granular role-based authorization (Student / Instructor / Admin).",
      "Built interactive video lessons, quiz checkpoints, and automated progress certificate triggers.",
      "Designed responsive admin consoles for course inventory, student enrollment metrics, and analytics.",
    ],
    metrics: {
      "Enrolled Students": "1,000+",
      "API Response": "55ms avg",
      "Test Coverage": "Comprehensive API Tests",
      "Design": "Mobile-First Fluid UI",
    },
    githubUrl: "https://github.com/abhimanyu840",
    liveUrl: "https://abhimanyukumarportfolio.netlify.app/",
    featured: false,
    order: 5,
  },
];

export const SEED_EXPERIENCE: IExperience[] = [
  {
    id: "wipro-se",
    company: "Wipro",
    role: "Software Engineer / Project Engineer",
    period: "2025 – Present",
    location: "Bengaluru, India",
    type: "Full-time",
    highlights: [
      "Develop and maintain enterprise monitoring and observability solutions using Python, FastAPI, React, Grafana, InfluxDB, and Prometheus.",
      "Build backend services and REST APIs for collecting, processing, storing, and exposing infrastructure monitoring data.",
      "Develop high-density operational dashboards for alerts, storage systems, SAN ports, performance metrics, and operational visibility.",
      "Work directly with enterprise storage platforms including NetApp ONTAP, Dell EMC, Hitachi VSP, and Brocade SAN switches.",
      "Integrate infrastructure telemetry through Syslog, SNMP, TCP/IP, and network-based monitoring mechanisms.",
      "Develop Python-based automation and listeners for processing infrastructure alerts and events in Linux/RHEL environments.",
      "Containerize and manage applications using Docker and Podman; troubleshoot services, ports, connectivity, and logging pipelines.",
      "Explore enterprise AI solutions including on-premise LLM deployment and RAG-based chatbot architectures.",
    ],
    techStack: [
      "Python",
      "FastAPI",
      "React",
      "Grafana",
      "InfluxDB",
      "Prometheus",
      "Linux/RHEL",
      "Docker/Podman",
      "NetApp",
      "Dell EMC",
      "Hitachi",
      "Brocade SAN",
      "SNMP",
      "Syslog",
    ],
  },
];

export const SEED_EDUCATION: IEducation[] = [
  {
    institution: "Birla Institute of Technology and Science (BITS Pilani)",
    degree: "Master of Technology (M.Tech)",
    program: "Software Systems (Wipro Work Integrated Learning Program)",
    period: "2025 – Present",
    status: "In Progress",
    details: [
      "Advanced coursework covering Distributed Computing, Cloud Architecture, Scalable Systems, and Software Engineering Methodologies.",
      "Sponsored via Wipro's prestigious Work Integrated Learning Program (WILP).",
    ],
  },
  {
    institution: "R.N. College, Bihar",
    degree: "Bachelor of Computer Applications (BCA)",
    period: "2021 – 2024",
    status: "Completed",
    details: [
      "Graduated with Distinction; strong foundational focus in Data Structures, Algorithms, Database Management Systems, and Object-Oriented Programming.",
    ],
  },
];

export const SEED_SKILL_GROUPS: ISkillGroup[] = [
  {
    category: "Languages & Core",
    description: "Core programming and scripting languages for production microservices & client apps",
    skills: [
      { name: "HTML5", level: 96, highlight: true },
      { name: "CSS3", level: 94, highlight: true },
      { name: "JavaScript (ES6+)", level: 92, highlight: true },
      { name: "TypeScript", level: 90, highlight: true },
      { name: "Python", level: 95, highlight: true },
      { name: "Bash / Shell Scripting", level: 88, highlight: true },
      { name: "Java", level: 75 },
    ],
  },
  {
    category: "Backend & APIs",
    description: "High-throughput asynchronous frameworks, REST interfaces, and validation systems",
    skills: [
      { name: "FastAPI", level: 94, highlight: true },
      { name: "Node.js", level: 90 },
      { name: "Express.js", level: 88 },
      { name: "RESTful API Design", level: 95, highlight: true },
      { name: "Zod Validation", level: 92, highlight: true },
      { name: "AsyncIO / Threading", level: 89 },
    ],
  },
  {
    category: "Observability & Telemetry",
    description: "Enterprise metric collection, alert propagation, and visual dashboarding suites",
    skills: [
      { name: "Grafana Dashboards", level: 95, highlight: true },
      { name: "InfluxDB (Time-Series)", level: 92, highlight: true },
      { name: "Prometheus & Exporters", level: 90, highlight: true },
      { name: "SNMP & Traps", level: 88 },
      { name: "Syslog Aggregation", level: 86 },
      { name: "TCP/IP & Network Monitoring", level: 87 },
    ],
  },
  {
    category: "Enterprise Storage & SAN",
    description: "Data center storage arrays, fabric switches, and SAN/NAS architectures",
    skills: [
      { name: "Brocade SAN Switches", level: 90, highlight: true },
      { name: "NetApp ONTAP", level: 88, highlight: true },
      { name: "Dell EMC Storage", level: 86 },
      { name: "Hitachi VSP Systems", level: 84 },
      { name: "Fibre Channel / SAN Ports", level: 88 },
      { name: "SAN/NAS Protocols", level: 86 },
    ],
  },
  {
    category: "DevOps, Linux & Containers",
    description: "Enterprise Linux administration, container virtualization, and deployment tooling",
    skills: [
      { name: "Linux / Red Hat (RHEL)", level: 92, highlight: true },
      { name: "Docker", level: 90, highlight: true },
      { name: "Podman", level: 88, highlight: true },
      { name: "Apache Web Server", level: 82 },
      { name: "Git & Version Control", level: 92 },
      { name: "Turborepo & Monorepos", level: 88 },
    ],
  },
  {
    category: "Frontend & Reactive UI",
    description: "Modern component-driven web frameworks, styling engines, and state management",
    skills: [
      { name: "React 19", level: 92, highlight: true },
      { name: "Next.js 16 (App Router)", level: 90, highlight: true },
      { name: "Tailwind CSS", level: 94, highlight: true },
      { name: "Vite", level: 88 },
      { name: "Redux Toolkit / Zustand", level: 85 },
      { name: "Responsive UI/UX", level: 92 },
    ],
  },
  {
    category: "Databases & AI Technologies",
    description: "Persistent storage, ODM modeling, and enterprise generative AI integration",
    skills: [
      { name: "MongoDB & Mongoose", level: 90, highlight: true },
      { name: "SQLite", level: 88 },
      { name: "MySQL", level: 85 },
      { name: "RAG Architectures", level: 86, highlight: true },
      { name: "Local LLMs (Ollama / NIM)", level: 85, highlight: true },
      { name: "Vector Search & Embeddings", level: 84 },
    ],
  },
];
